[tool.poetry]
name = "nrkvisual"
version = "0.1.4"
description = ""
authors = ["mjaquier <mjaquier@mjaquier.xyz>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.2"
matplotlib = "^3.3.2"
numpy = "^1.19.2"
xlrd = "^1.2.0"
chardet = "^3.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
