[tool.poetry]
name = "pengu"
version = "0.1.1"
description = "WIP"
authors = ["peachanG <kenkman0427@gmail.com>"]
homepage = "https://github.com/peachanG"
repository = "https://github.com/peachanG/pengu"
documentation = "https://peachang.github.io/pengu/"
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.6"
tensorflow = "2.3.0"
icrawler = "^0.6.3"
mypy = "^0.782"
mlflow = "^1.10.0"
hydra = "^2.5"
opencv-python = "4.2.0.34"
imagehash = "^4.1.0"
scikit-learn = "^0.23.2"
matplotlib = "^3.3.0"
tensorboard_plugin_profile = "^2.3.0"
boto3 = "^1.14.38"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.9.0"
jupyterlab = "^2.2.4"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
